[project]
name = "backend"
version = "0.1.0"
description = "DocsReview.AI Backend"
readme = "../../note/backend.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "google-genai>=1.28.0",
]
